CLASS zcl_980_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF Z980_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_980_handler IMPLEMENTATION.
ENDCLASS.
